#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run update-docs
npx lint-staged
npm run typecheck
npm run test -- --runInBand --passWithNoTests
npm run validate:deps
npm run validate:boundaries
