import { inject, injectable } from 'inversify';
import { IUserRepository } from '../../domain/repositories/IUserRepository';
import { UserEntity, UserRole } from '../../domain/entities/User';
import { Password } from '../../domain/value-objects/Password';
import { Email } from '../../domain/value-objects/Email';
import { RegisterUserDTO, AuthResponseDTO } from '../dtos/AuthDTOs';
import { IAuthService } from '../services/IAuthService';

@injectable()
export class RegisterUserUseCase {
  constructor(
    @inject('IUserRepository') private userRepository: IUserRepository,
    @inject('IAuthService') private authService: IAuthService,
  ) {}

  async execute(dto: RegisterUserDTO): Promise<AuthResponseDTO> {
    // Check if user already exists
    const existingUser = await this.userRepository.findByEmail(dto.email);
    if (existingUser) {
      throw new Error('User already exists with this email');
    }

    // Create value objects
    const email = new Email(dto.email);
    const password = await Password.create(dto.password);

    // Create user entity
    const user = new UserEntity(
      '', // ID will be generated by repository
      email.getValue(),
      password.getHashedValue(),
      dto.firstName,
      dto.lastName,
      UserRole.CUSTOMER,
    );

    // Save user
    const savedUser = await this.userRepository.create(user);

    // Generate tokens
    const tokens = await this.authService.generateTokens(savedUser);

    return {
      user: {
        id: savedUser.id,
        email: savedUser.email,
        firstName: savedUser.firstName,
        lastName: savedUser.lastName,
        role: savedUser.role,
      },
      accessToken: tokens.accessToken,
      refreshToken: tokens.refreshToken,
    };
  }
}